import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import {
  Award,
  BookOpen,
  Brain,
  Briefcase,
  CalendarDays,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  FileText,
  FileUp,
  GraduationCap,
  PlayCircle,
  Sparkles,
  Target,
  X,
} from 'lucide-react'
import { useNavigate } from 'react-router-dom'

const GUIDE_STEPS = [
  {
    id: 'resume',
    stepNumber: 1,
    title: 'Upload Your Resume / CV',
    subtitle: 'The foundation for AI matching',
    icon: FileUp,
    badge: 'Step 1: Essential',
    badgeColor: 'bg-blue-50 text-blue-700 border-blue-200',
    description:
      'Upload your updated PDF resume. RecruitSense AI automatically extracts your technical skills, work experience, projects, and domain expertise in seconds.',
    tips: [
      'Use a clean, standard PDF resume layout for best AI parsing.',
      'AI automatically indexes your profile into our secure ChromaDB vector database.',
    ],
    actionText: 'Go to Resume Upload',
    actionPath: '/resume/upload',
    actionIcon: FileUp,
    gradient: 'from-blue-500 to-indigo-600',
    bgGradient: 'from-blue-50/70 via-indigo-50/30 to-white',
  },
  {
    id: 'browse',
    stepNumber: 2,
    title: 'Explore & Apply for Jobs',
    subtitle: 'Real-time AI Match Scoring',
    icon: Briefcase,
    badge: 'Step 2: Opportunities',
    badgeColor: 'bg-purple-50 text-purple-700 border-purple-200',
    description:
      'Browse through verified company listings or visit "Recommended Jobs". When you apply, our Hybrid AI (Dense Vectors + Semantic Skill Extractor) instantly analyzes your compatibility.',
    tips: [
      'You get an instant Resume Similarity Score (50% weight) and Skill Match Score (30% weight).',
      'You can apply with 1-click once your resume is uploaded.',
    ],
    actionText: 'Browse Open Jobs',
    actionPath: '/jobs',
    actionIcon: Briefcase,
    gradient: 'from-purple-500 to-pink-600',
    bgGradient: 'from-purple-50/70 via-pink-50/30 to-white',
  },
  {
    id: 'quiz',
    stepNumber: 3,
    title: 'Take the Soft Skills AI Quiz',
    subtitle: 'Unlock +20% Score & Auto-Shortlisting',
    icon: Brain,
    badge: 'Step 3: Crucial Step',
    badgeColor: 'bg-emerald-50 text-emerald-700 border-emerald-200',
    description:
      'After applying, visit "My Applications". Click "Take Soft Skills Quiz" to answer 5 interactive multiple-choice questions dynamically generated by AI for your role.',
    tips: [
      'Soft skills account for 20% of your Final Candidate Match Score.',
      'Achieving a total score of 75% or higher automatically qualifies you for AI Auto-Shortlisting!',
    ],
    actionText: 'View My Applications',
    actionPath: '/my-applications',
    actionIcon: Brain,
    gradient: 'from-emerald-500 to-teal-600',
    bgGradient: 'from-emerald-50/70 via-teal-50/30 to-white',
  },
  {
    id: 'skills',
    stepNumber: 4,
    title: 'Skill Gaps & In-App Learning',
    subtitle: 'Learn missing skills right inside the app',
    icon: GraduationCap,
    badge: 'Step 4: Continuous Growth',
    badgeColor: 'bg-amber-50 text-amber-700 border-amber-200',
    description:
      'RecruitSense compares required job skills with your resume. Any missing skill is highlighted with AI-recommended courses from freeCodeCamp, Coursera, and YouTube.',
    tips: [
      'Watch full video tutorials directly inside our In-App Video Player without leaving the app.',
      'Upskilling on identified gaps increases your score for similar upcoming job postings.',
    ],
    actionText: 'Check Recommended Jobs',
    actionPath: '/recommended-jobs',
    actionIcon: GraduationCap,
    gradient: 'from-amber-500 to-orange-600',
    bgGradient: 'from-amber-50/70 via-orange-50/30 to-white',
  },
  {
    id: 'shortlist',
    stepNumber: 5,
    title: 'Track Status & Interview Schedule',
    subtitle: 'Stay updated in real time',
    icon: CalendarDays,
    badge: 'Step 5: Hiring Pipeline',
    badgeColor: 'bg-indigo-50 text-indigo-700 border-indigo-200',
    description:
      'Track your hiring journey with live pipeline stages: Pending ➔ Screening ➔ Shortlisted ➔ Interview Scheduled ➔ Offer! Receive instant in-app and email notifications.',
    tips: [
      'Interview dates, Google Meet links, and physical locations appear directly in your Application Timeline.',
      'Employers can chat with you and send job offers directly through RecruitSense.',
    ],
    actionText: 'Go to Dashboard',
    actionPath: '/dashboard',
    actionIcon: Target,
    gradient: 'from-indigo-600 to-blue-700',
    bgGradient: 'from-indigo-50/70 via-blue-50/30 to-white',
  },
]

const OnboardingGuideModal = ({ isOpen, onClose }) => {
  const navigate = useNavigate()
  const [currentStepIndex, setCurrentStepIndex] = useState(0)
  const [dontShowAgain, setDontShowAgain] = useState(false)

  if (!isOpen) return null

  const currentStep = GUIDE_STEPS[currentStepIndex]
  const isFirstStep = currentStepIndex === 0
  const isLastStep = currentStepIndex === GUIDE_STEPS.length - 1

  const handleClose = () => {
    if (dontShowAgain) {
      localStorage.setItem('recruitsense_jobseeker_guide_seen', 'true')
    }
    onClose()
  }

  const handleAction = (path) => {
    handleClose()
    navigate(path)
  }

  const handleNext = () => {
    if (isLastStep) {
      handleClose()
    } else {
      setCurrentStepIndex((prev) => prev + 1)
    }
  }

  const handlePrev = () => {
    if (!isFirstStep) {
      setCurrentStepIndex((prev) => prev - 1)
    }
  }

  const StepIcon = currentStep.icon

  return (
    <div className="fixed inset-0 z-50 bg-gray-900/60 backdrop-blur-xs flex items-center justify-center p-4">
      <motion.div
        initial={{ opacity: 0, scale: 0.95, y: 10 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.95, y: 10 }}
        transition={{ duration: 0.2 }}
        className="bg-white rounded-3xl shadow-2xl w-full max-w-2xl overflow-hidden flex flex-col border border-gray-100"
      >
        {/* Top Header */}
        <div className="px-6 py-4 border-b border-gray-100 flex items-center justify-between bg-gray-50/60">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-xl bg-gradient-to-tr from-indigo-600 to-purple-600 text-white flex items-center justify-center shadow-sm">
              <Sparkles className="w-4 h-4" />
            </div>
            <div>
              <h3 className="text-sm font-bold text-gray-900">Job Seeker Quick Guide</h3>
              <p className="text-[11px] text-gray-500">Step {currentStep.stepNumber} of {GUIDE_STEPS.length}</p>
            </div>
          </div>

          <div className="flex items-center gap-3">
            <button
              onClick={handleClose}
              className="w-8 h-8 rounded-full hover:bg-gray-200/60 flex items-center justify-center text-gray-400 hover:text-gray-700 transition-colors"
              aria-label="Close guide"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Stepper Progress Bar */}
        <div className="px-6 pt-4 pb-1">
          <div className="grid grid-cols-5 gap-2">
            {GUIDE_STEPS.map((step, idx) => {
              const isActive = idx === currentStepIndex
              const isPassed = idx < currentStepIndex
              return (
                <button
                  key={step.id}
                  onClick={() => setCurrentStepIndex(idx)}
                  className="group flex flex-col gap-1.5 text-left focus:outline-none"
                >
                  <div
                    className={`h-1.5 w-full rounded-full transition-all duration-300 ${
                      isActive
                        ? 'bg-indigo-600'
                        : isPassed
                        ? 'bg-emerald-500'
                        : 'bg-gray-200'
                    }`}
                  />
                  <span
                    className={`text-[10px] font-bold hidden sm:block truncate ${
                      isActive
                        ? 'text-indigo-600'
                        : isPassed
                        ? 'text-gray-600'
                        : 'text-gray-400'
                    }`}
                  >
                    {step.stepNumber}. {step.title.split(' ')[0]}
                  </span>
                </button>
              )
            })}
          </div>
        </div>

        {/* Main Content Area */}
        <div className="p-6">
          <AnimatePresence mode="wait">
            <motion.div
              key={currentStep.id}
              initial={{ opacity: 0, x: 15 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -15 }}
              transition={{ duration: 0.2 }}
              className={`rounded-2xl border border-gray-100 bg-gradient-to-br ${currentStep.bgGradient} p-5 sm:p-6`}
            >
              <div className="flex items-start gap-4">
                <div
                  className={`w-12 h-12 rounded-2xl bg-gradient-to-tr ${currentStep.gradient} text-white flex items-center justify-center flex-shrink-0 shadow-md shadow-indigo-500/20`}
                >
                  <StepIcon className="w-6 h-6" />
                </div>

                <div className="flex-1">
                  <div className="flex flex-wrap items-center gap-2 mb-1">
                    <span
                      className={`text-[10px] font-extrabold uppercase px-2.5 py-0.5 rounded-full border ${currentStep.badgeColor}`}
                    >
                      {currentStep.badge}
                    </span>
                    <span className="text-xs font-semibold text-gray-500">
                      {currentStep.subtitle}
                    </span>
                  </div>

                  <h4 className="text-lg font-extrabold text-gray-900 mt-1">
                    {currentStep.title}
                  </h4>

                  <p className="text-sm text-gray-700 leading-relaxed mt-2">
                    {currentStep.description}
                  </p>

                  <div className="mt-4 pt-3 border-t border-gray-200/60 space-y-2">
                    {currentStep.tips.map((tip, i) => (
                      <div key={i} className="flex items-start gap-2 text-xs text-gray-600">
                        <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600 mt-0.5 flex-shrink-0" />
                        <span>{tip}</span>
                      </div>
                    ))}
                  </div>

                  {/* Direct Step Action Button */}
                  <div className="mt-5">
                    <button
                      type="button"
                      onClick={() => handleAction(currentStep.actionPath)}
                      className={`inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-gradient-to-r ${currentStep.gradient} text-white text-xs font-bold shadow-sm hover:opacity-95 transition-all`}
                    >
                      <currentStep.actionIcon className="w-4 h-4" />
                      <span>{currentStep.actionText}</span>
                    </button>
                  </div>
                </div>
              </div>
            </motion.div>
          </AnimatePresence>
        </div>

        {/* Footer Navigation Controls */}
        <div className="px-6 py-4 border-t border-gray-100 bg-white flex flex-col sm:flex-row items-center justify-between gap-3">
          <label className="flex items-center gap-2 text-xs text-gray-500 cursor-pointer self-start sm:self-center">
            <input
              type="checkbox"
              checked={dontShowAgain}
              onChange={(e) => setDontShowAgain(e.target.checked)}
              className="rounded border-gray-300 text-indigo-600 focus:ring-indigo-500 w-3.5 h-3.5"
            />
            <span>Don't show automatically next time</span>
          </label>

          <div className="flex items-center gap-2 w-full sm:w-auto justify-end">
            {!isFirstStep && (
              <button
                type="button"
                onClick={handlePrev}
                className="px-3.5 py-2 rounded-xl border border-gray-200 text-gray-700 text-xs font-bold hover:bg-gray-50 flex items-center gap-1 transition-colors"
              >
                <ChevronLeft className="w-4 h-4" />
                <span>Back</span>
              </button>
            )}

            <button
              type="button"
              onClick={handleNext}
              className="px-5 py-2 rounded-xl bg-indigo-600 text-white text-xs font-bold hover:bg-indigo-700 flex items-center gap-1 shadow-sm transition-all"
            >
              <span>{isLastStep ? 'Finish & Explore' : 'Next Step'}</span>
              <ChevronRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      </motion.div>
    </div>
  )
}

export default OnboardingGuideModal
